env: "local"
datastore:
  storage:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "postgres"
    dbname: "postgres"
    sslmode: "disable"
  cache:
    addr: "localhost:6379"
    password: ""
    db: 0
    max_retries: 3
    dial_timeout: 10s
    timeout: 5s
clients:
  sso:
    address: "localhost:8081"
    timeout: 1h
    retries_count: 5
    app_id: 1
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
